import { jsPDF } from 'jspdf';
import type { CompressionLevel } from './imageCompression';
import { getZorPdfFileName } from './fileNaming';

export interface CompressionResult {
  blob: Blob;
  filename: string;
  originalSize: number;
  pdfSize: number;
  compressionRatio: number;
  pageWidth: number;
  pageHeight: number;
  imageCount: number;
  compressionLevel: CompressionLevel;
  adaptiveQuality: number;
}

export async function convertImagesToPdf(
  files: File[],
  compressionLevel: CompressionLevel = 'balanced'
): Promise<CompressionResult> {
  let totalOriginalSize = 0;

  const pdf = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();

  for (let index = 0; index < files.length; index++) {
    const file = files[index];
    totalOriginalSize += file.size;

    const imgUrl = URL.createObjectURL(file);
    const img = new Image();

    await new Promise<void>((resolve, reject) => {
      img.onload = () => resolve();
      img.onerror = () => reject(new Error(`Failed to load image: ${file.name}`));
      img.src = imgUrl;
    });

    const canvas = document.createElement('canvas');
    canvas.width = img.width;
    canvas.height = img.height;

    const ctx = canvas.getContext('2d');
    if (!ctx) throw new Error('Failed to get canvas context');
    ctx.drawImage(img, 0, 0);

    const quality = compressionLevel === 'high' ? 0.6 : compressionLevel === 'balanced' ? 0.75 : 0.9;
    const imgData = canvas.toDataURL('image/jpeg', quality);

    const imgWidth = pageWidth - 10;
    const imgHeight = (img.height * imgWidth) / img.width;

    if (index > 0) {
      pdf.addPage();
    }

    pdf.addImage(imgData, 'JPEG', 5, 5, imgWidth, imgHeight);

    pdf.setFontSize(8);
    pdf.text('Generated by zorPDF.com', 10, pageHeight - 10);

    URL.revokeObjectURL(imgUrl);
  }

  const pdfBlob = pdf.output('blob');
  const filename = getZorPdfFileName('pdf');

  return {
    blob: pdfBlob,
    filename,
    originalSize: totalOriginalSize,
    pdfSize: pdfBlob.size,
    compressionRatio: totalOriginalSize / pdfBlob.size,
    pageWidth,
    pageHeight,
    imageCount: files.length,
    compressionLevel,
    adaptiveQuality: compressionLevel === 'high' ? 0.6 : compressionLevel === 'balanced' ? 0.75 : 0.9,
  };
}
