import { PDFDocument, rgb } from 'pdf-lib';

export interface CompressionResult {
  blob: Blob;
  filename: string;
  originalSize: number;
  compressedSize: number;
  compressionRatio: number;
}

export async function compressPdf(
  pdfFile: File,
  compressionLevel: 'low' | 'medium' | 'high' = 'medium'
): Promise<CompressionResult> {
  try {
    const arrayBuffer = await pdfFile.arrayBuffer();
    const pdfDoc = await PDFDocument.load(arrayBuffer);

    pdfDoc.setTitle('');
    pdfDoc.setAuthor('');
    pdfDoc.setSubject('');
    pdfDoc.setKeywords([]);
    pdfDoc.setProducer('zorPDF.com');
    pdfDoc.setCreator('zorPDF.com');

    const pages = pdfDoc.getPages();
    for (const page of pages) {
      page.drawText('Generated by zorPDF.com', {
        x: 20,
        y: 15,
        size: 10,
        color: rgb(0.7, 0.7, 0.7),
      });
    }

    const compressedPdfBytes = await pdfDoc.save({ useObjectStreams: compressionLevel === 'high' });
    const compressedBlob = new Blob([compressedPdfBytes], { type: 'application/pdf' });

    const baseName = pdfFile.name.replace(/\.[^.]+$/, '');
    const filename = `zorPDF.com-${baseName}-compressed.pdf`;

    return {
      blob: compressedBlob,
      filename,
      originalSize: pdfFile.size,
      compressedSize: compressedBlob.size,
      compressionRatio: pdfFile.size / compressedBlob.size,
    };
  } catch (err) {
    throw new Error(`Failed to compress PDF: ${err instanceof Error ? err.message : 'Unknown error'}`);
  }
}
