Bilkul bhai. **`lib/pdfMerger.ts` ka poora code** neeche hai. Is version mein:

* `Generated by zorPDF.com` hata diya hai
* Image **top se start hogi**
* Horizontal center rahegi
* Aspect ratio preserve rahega
* Image stretch/crop nahi hogi
* Portrait = A4 Portrait
* Landscape = A4 Landscape

```ts
import { PDFDocument, PDFImage } from 'pdf-lib';
import type { CompressionLevel } from './imageCompression';
import { compressImage } from './imageCompression';
import { getZorPdfFileName } from './fileNaming';

export interface ImageProcessingResult {
  id: string;
  file: File;
  thumbnail: string;
  width: number;
  height: number;
  compressedBlob?: Blob;
}

export interface MergeResult {
  blob: Blob;
  filename: string;
  pageCount: number;
  originalSize: number;
  pdfSize: number;
  compressionRatio: number;
}

/**
 * Generate thumbnail for preview
 */
export async function generateThumbnail(
  file: File,
  maxSize: number = 150
): Promise<string> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();

    reader.onload = (event) => {
      const img = new Image();

      img.onload = () => {
        const canvas = document.createElement('canvas');

        let width = img.width;
        let height = img.height;

        if (width > height) {
          if (width > maxSize) {
            height = Math.round((height * maxSize) / width);
            width = maxSize;
          }
        } else {
          if (height > maxSize) {
            width = Math.round((width * maxSize) / height);
            height = maxSize;
          }
        }

        canvas.width = width;
        canvas.height = height;

        const ctx = canvas.getContext('2d');

        if (!ctx) {
          reject(new Error('Failed to create canvas context'));
          return;
        }

        ctx.imageSmoothingEnabled = true;
        ctx.imageSmoothingQuality = 'high';

        ctx.drawImage(img, 0, 0, width, height);

        resolve(canvas.toDataURL('image/jpeg', 0.7));
      };

      img.onerror = () => {
        reject(new Error('Failed to load image'));
      };

      img.src = event.target?.result as string;
    };

    reader.onerror = () => {
      reject(new Error('Failed to read file'));
    };

    reader.readAsDataURL(file);
  });
}

/**
 * Load image information
 */
export async function loadImageInfo(
  file: File
): Promise<{
  width: number;
  height: number;
  thumbnail: string;
}> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();

    reader.onload = (event) => {
      const img = new Image();

      img.onload = async () => {
        try {
          const thumbnail = await generateThumbnail(file);

          resolve({
            width: img.width,
            height: img.height,
            thumbnail,
          });
        } catch (error) {
          reject(error);
        }
      };

      img.onerror = () => {
        reject(new Error('Failed to load image'));
      };

      img.src = event.target?.result as string;
    };

    reader.onerror = () => {
      reject(new Error('Failed to read file'));
    };

    reader.readAsDataURL(file);
  });
}

/**
 * Process image before adding it to the PDF
 */
export async function processImageForPdf(
  file: File,
  compressionLevel: CompressionLevel
): Promise<{
  blob: Blob;
  width: number;
  height: number;
}> {
  // Low compression: keep original dimensions
  if (compressionLevel === 'low') {
    return new Promise((resolve, reject) => {
      const reader = new FileReader();

      reader.onload = (event) => {
        const img = new Image();

        img.onload = () => {
          const canvas = document.createElement('canvas');

          canvas.width = img.width;
          canvas.height = img.height;

          const ctx = canvas.getContext('2d');

          if (!ctx) {
            reject(new Error('Failed to create canvas'));
            return;
          }

          ctx.drawImage(img, 0, 0);

          canvas.toBlob(
            (blob) => {
              if (!blob) {
                reject(new Error('Failed to create image blob'));
                return;
              }

              resolve({
                blob,
                width: img.width,
                height: img.height,
              });
            },
            'image/jpeg',
            0.92
          );
        };

        img.onerror = () => {
          reject(new Error('Failed to load image'));
        };

        img.src = event.target?.result as string;
      };

      reader.onerror = () => {
        reject(new Error('Failed to read file'));
      };

      reader.readAsDataURL(file);
    });
  }

  // Other compression levels
  const result = await compressImage(file, compressionLevel);

  return {
    blob: result.blob,
    width: result.newWidth,
    height: result.newHeight,
  };
}

/**
 * Merge all uploaded images into one PDF.
 *
 * - No "Generated by zorPDF.com" footer
 * - Standard A4 page
 * - Image keeps original aspect ratio
 * - Image is NOT stretched
 * - Image is NOT cropped
 * - Image starts from the TOP of the page
 */
export async function mergeImagesToPdf(
  images: ImageProcessingResult[],
  compressionLevel: CompressionLevel,
  onProgress?: (
    current: number,
    total: number,
    imageId: string
  ) => void
): Promise<MergeResult> {
  if (images.length === 0) {
    throw new Error('No images to merge');
  }

  const pdfDoc = await PDFDocument.create();

  let totalOriginalSize = 0;

  // A4 dimensions in PDF points
  const A4_WIDTH = 595.28;
  const A4_HEIGHT = 841.89;

  for (let i = 0; i < images.length; i++) {
    const imageInfo = images[i];
    const file = imageInfo.file;

    totalOriginalSize += file.size;

    if (onProgress) {
      onProgress(i + 1, images.length, imageInfo.id);
    }

    // Process image
    const { blob, width, height } = await processImageForPdf(
      file,
      compressionLevel
    );

    const arrayBuffer = await blob.arrayBuffer();

    let pdfImage: PDFImage;

    // Embed JPG or PNG
    try {
      pdfImage = await pdfDoc.embedJpg(arrayBuffer);
    } catch {
      try {
        pdfImage = await pdfDoc.embedPng(arrayBuffer);
      } catch {
        throw new Error(
          `Failed to embed image: ${file.name}`
        );
      }
    }

    // Detect image orientation
    const isLandscape = width > height;

    // Portrait image = A4 Portrait
    // Landscape image = A4 Landscape
    const pageWidth = isLandscape
      ? A4_HEIGHT
      : A4_WIDTH;

    const pageHeight = isLandscape
      ? A4_WIDTH
      : A4_HEIGHT;

    // Create A4 page
    const page = pdfDoc.addPage([
      pageWidth,
      pageHeight,
    ]);

    // Calculate scale so image fits fully inside page
    // while preserving aspect ratio
    const scale = Math.min(
      pageWidth / width,
      pageHeight / height
    );

    const drawWidth = width * scale;
    const drawHeight = height * scale;

    // Center horizontally
    const x = (pageWidth - drawWidth) / 2;

    // IMPORTANT:
    // PDF coordinates start from the bottom.
    // This places the image exactly at the TOP.
    const y = pageHeight - drawHeight;

    // Draw image at the TOP of the page
    page.drawImage(pdfImage, {
      x,
      y,
      width: drawWidth,
      height: drawHeight,
    });

    // No footer is added here.
    // "Generated by zorPDF.com" has been removed.
  }

  // Save PDF
  const pdfBytes = await pdfDoc.save();

  const blob = new Blob(
    [pdfBytes],
    {
      type: 'application/pdf',
    }
  );

  const filename = getZorPdfFileName('pdf');

  return {
    blob,
    filename,
    pageCount: images.length,
    originalSize: totalOriginalSize,
    pdfSize: blob.size,
    compressionRatio:
      totalOriginalSize > 0 && blob.size > 0
        ? totalOriginalSize / blob.size
        : 1,
  };
}

/**
 * Read file as ArrayBuffer
 */
export function readFileAsArrayBuffer(
  file: File
): Promise<ArrayBuffer> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();

    reader.onload = (event) => {
      resolve(event.target?.result as ArrayBuffer);
    };

    reader.onerror = () => {
      reject(new Error('Failed to read file'));
    };

    reader.readAsArrayBuffer(file);
  });
}
```
